### PR TITLE
Extract WebView code to new AwfulWebView class and utilities

### PR DESCRIPTION
**Pull request by baka-kaba**
Pulled out most WebView configuration code into several components:
- an AwfulWebView class with some common methods and lifecycle handling
- a WebViewConfig class that does most of the setup that was previously
  in the containing fragments
- LoggingWebChromeClient, which is the basic client with logging calls,
  previously used in one class but now easy to subclass and drop in anywhere
- WebViewJsInterface, holding common JavascriptInterface-annotated methods

The idea is to get all that stuff out of the fragments holding the webviews,
get the code all in one place, and make the configuration and interaction calls
as minimal as possible.

There are still some changes to make (lots of TODOs),
partly removing some old config code and maybe pushing it all into AwfulWebView
as a generic init call, and partly getting some of the remaining WebView-poking
code out of the fragments (they shouldn't need to make direct load calls with
base URLs and html and charsets and stuff - need simple utility methods for that)

### CODE REVIEW

**Comment by baka-kaba** [comment]
Am I all right merging this in?

I've been testing it a while, I'm pretty sure everything works as it did - might want to check the post previews though

**Comment by Sereri** [comment]
I think so, seems alright. Will test it tonight.

I'm pretty sure we already had a AwfulWebview once but I think it was just a wrapper for ... some reason I don't remember and became redundant in some later version of android.

**Comment by baka-kaba** [comment]
Yeah a file with that name was already being tracked by Git, spooky

There's a bunch of redundant code in there - I refactored all the setup code as methods in one class, and tried making all the webviews use the main setup method, which worked fine. So those old methods are basically legacy code and the class isn't really needed, we can just have all the setup stuff in AwfulWebView

I was thinking it might be easier to add another commit removing all that, so that if there *is* a problem it's easy to go back and find how things used to be set up for each component

**Comment by baka-kaba** [comment]
Sorry, fixed that regression (that I artisanally merged by hand thanks git)

**Comment by Sereri** [comment]
Seems to work fine in all 3 cases. Are the TODOs anything serious?

**Comment by baka-kaba** [comment]
Nah they're either stuff that was in the original code (like WebView config warnings) or things to keep in mind for the future

**Pull request merged**
