### PR TITLE
Create Forums package with update/sync tasks, new forum index

### PR DESCRIPTION
**Pull request by baka-kaba**
Added a Forums package responsible for updating and providing access
to forum data.

ForumRepository handles async updates with callbacks, handles database actions,
and provides access to data as ForumStructures.
ForumStructure is a representation of the forum hierarchy, which can produce
customisable list and tree formats.
Forum encapsulates the data associated with a forum, with some utility functions.

Also reworked the forum index page - now it uses a RecyclerView and the
new ForumStructure system to make a customisable list. There's a TagProvider class
which handles setting forum tag views, and a SquareForumTag class which is a
specific implementation using Sereri's graphic and with a dynamic text overlay.

Added a new settings category for the forums list, and with a force update option.

Also included a SyncManager class to run necessary update/sync tasks on app start
and login. Forum data updates once a week at low priority, unless there's no data,
in which case there's a high priority update and a basic fallback update if it fails.

Upgraded database version to force a forum data clear, since old data will
look messed up with the new Forums system data

Data limiting uses the user's 'download images on 3G' setting to restrict
low-priority forum updates. This could probably do with a proper setting
for limiting data in general, maybe as a single option or with granular settings.

Basic square thread tags, generated
(cherry picked from commit 84bea58)

### CODE REVIEW

**Comment by Sereri** [comment]
Looking very good (shame about having to hardcode all the forum shortnames but whaddayagonnado)

I think there might be a small bug when the parsing is finished but the view is not visible. The view just keeps on "loading" until the app is fully closed and reopened.

**Comment by Sereri** [comment]
By the way, I'm almost instantly turned off section headers and subtitles (because I hate change). Looking very nice either way.

**Comment by baka-kaba** [comment]
That's why I made them optional! To avoid complai- I mean, because freedom of choice is good! (It's still gonna happen though, remember when thread items got slightly taller...)

Good catch on the refresh bug, thanks - I had it refreshing in onResume before, but that reset the index every time and I moved it earlier in the lifecycle. Looks like I forgot what else happens! Looks like it's only when the activity isn't visible (like if you're in Settings), I've fixed it up and tweaked a few other things too

**Comment by Sereri** [comment]
Ok, I think this is almost ready. Looking through the changes I think we should rename forumtagtest.png to something else.

Speaking of which, I also tried another one without the black borders and I like it a little bit better:

forumtagtest_new

What do you think? I still think it could use a bit of texture like the thread tags (see computers, misogyny or comedy) but I'm terrible at photoshop etc. Maybe we can get @diabolik900 or someone else from the Awful.app guys to hook us up.

**Comment by diabolik900** [comment]
Happy to lend a hand if I can, but I can't see your image. I assume it's the same forumtagtest.png image that you mentioned earlier in your comment?

**Comment by Sereri** [comment]
That would be great.
And I removed the black lines so it's only white and transparent now, with the white github background there's not much to see here. Try clicking on the empty space.

Anyway, I'm gonna merge this and shift the discussion back to #349

**Pull request merged**
