### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by baka-kaba**
I took care of a few issues on Crashlytics

### CODE REVIEW

**Comment by Sereri** [comment]
whats with the disable Crashlytics commit?

**Comment by baka-kaba** [comment]
Oh I always do that so I can skip it when I rebase, otherwise I'll forget. Is that awkward? I figured it would be easy to ignore when you're merging stuff in, but that's just me assuming things

**Comment by Sereri** [comment]
Merging stuff in is me pressing a button on github (unless there are conflicts). The crashlytics thing would be automatically merged in.

**Comment by baka-kaba** [comment]
My bad! They're gone now

**Pull request merged**
